[build]
  base = "shopping-app"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--openssl-legacy-provider"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
